# Generated by Django 6.0.4 on 2026-04-26 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='massege',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
