# Generated by Django 6.0.4 on 2026-04-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about_info', models.CharField(max_length=300)),
                ('discription', models.TextField(max_length=500)),
            ],
        ),
    ]
